### ISSUE TITLE
Rename `user` to `player`

### ISSUE THREAD

**Issue by oversword** [AKhilRaghav0/hawk-mod#2]
Not a major issue, but this should be player for 2 reasons:
1. it is passed in as `player`, it's much easier to follow if it's named the same thing in the call and the definition. So long as it is possible & makes sense to do that it should be done
2. When talking about this kind of thing with other mod developers I've found it's best to differentiate between the player - who uses the game, and the user - who uses the engine. We, the mod creators, are the users of minetest, the people who use our mods are the players

https://github.com/AKhilRaghav0/hawk-mod/blob/f77513ba1122b32400707569afacf3423970f960/flight.lua#L27

**Comment by AKhilRaghav0** [comment]
Okay Renamed
